<h4> Taller 3 - Joaquin Suarez </h4>

<h5> Punto 1 </h5>

In [1]:
import math
import numpy as np
import pylab as pl
import random as rnd
import time
import sys
%matplotlib inline

In [2]:
class Counter:
    def __init__(self):
        self.steps = 0

    def reset(self):
        self.steps = 0

    def count(self):
        self.steps += 1

    def print_steps(self):
        print "Number of steps =", self.steps

In [3]:
def maxSubArraySum(a,size):
     
    max_so_far = 0
    max_ending_here = 0
     
    for i in range(0, size):
        max_ending_here = max_ending_here + a[i]
        if max_ending_here < 0:
            max_ending_here = 0
         
        elif (max_so_far < max_ending_here):
            max_so_far = max_ending_here
             
    return max_so_far

In [4]:
m= np.random.randint(9, size=(6)) # de 0 a 9
print m
r=maxSubArraySum(m,6)
print r

[3 1 4 6 8 5]
27


In [5]:
def acctMaxSubArraySum(a,size, acct):
     
    max_so_far = 0; acct.count()
    max_ending_here = 0; acct.count()
     
    for i in range(0, size):
        acct.count()
        max_ending_here = max_ending_here + a[i]; acct.count()
        if max_ending_here < 0:
            acct.count()
            max_ending_here = 0; acct.count()
         
        elif (max_so_far < max_ending_here):
            acct.count()
            max_so_far = max_ending_here; acct.count()
             
    return max_so_far

In [6]:
m= np.random.randint(9, size=(6)) # de 0 a 9
print m
acct= Counter()
r=acctMaxSubArraySum(m,6,acct)
print r
acct.print_steps()

[6 7 1 2 2 5]
23
Number of steps = 26


<h5>Punto 2</h5>

In [7]:
def max_crossover(a,start,middle,end):
    currentLeftSum = 0
    leftSum = -sys.maxint - 1
    currentRightSum = 0
    rightSum =-sys.maxint - 1
    for i in range(middle, start, -1):
        currentLeftSum += a[i]
        if currentLeftSum > leftSum:
            leftSum = currentLeftSum
    for i in range(middle, end):
        currentRightSum += a[i]
        if currentRightSum > rightSum:
            rightSum = currentRightSum
    return leftSum + rightSum




In [8]:
def max_subarray(a,start,end):
    #end=len(a)
    if start == end:
        return a[start]
    else:
        middle = (start + end) / 2
        return max(max_subarray(a, start, middle), max_subarray(a,middle + 1, end), max_crossover(a, start, middle, end))



In [9]:
m= np.random.randint(9, size=(6)) # de 0 a 9
print m
n = len(m)-1
r=max_subarray(m,0,n)
print r

[5 4 5 3 5 1]
22


In [10]:
def max_crossover(a,start,middle,end,acct):
    currentLeftSum = 0; acct.count()
    leftSum = -sys.maxint - 1; acct.count()
    currentRightSum = 0; acct.count()
    rightSum =-sys.maxint - 1; acct.count()
    for i in range(middle, start, -1):
        acct.count()
        currentLeftSum += a[i]; acct.count()
        if currentLeftSum > leftSum:
            acct.count()
            leftSum = currentLeftSum; acct.count()
    for i in range(middle, end):
        acct.count()
        currentRightSum += a[i]; acct.count()
        if currentRightSum > rightSum:
            acct.count()
            rightSum = currentRightSum; acct.count()
    return leftSum + rightSum

def acctMax_subarray(a,start,end,acct):
    #end=len(a)
    if start == end:
        acct.count()
        return a[start]
    else:
        middle = (start + end) / 2; acct.count()
        return max(acctMax_subarray(a, start, middle,acct), acctMax_subarray(a,middle + 1, end,acct), max_crossover(a, start, middle, end,acct))

In [11]:
m= np.random.randint(9, size=(6)) # de 0 a 9
print m
n = len(m)-1
acct= Counter()
r=acctMax_subarray(m,0,n,acct)
print r
acct.print_steps()

[7 8 4 7 7 7]
30
Number of steps = 75


<h5>Punto 3</h5>

In [12]:
def max2(a,b):
    if a<b:
        return b
    else:
        return a
    
def sumaMax3(a,x,y):
    if x > y:
        return 0
    if x == y:
        return max2(0,a[x])
    m = ((x + y)/2)
    
    maxAux= max2(sumaMax3(a,x,m),
                 sumaMax3(a,m + 1,y))
    
    vp=0;
    s=0
    for i in range(m,x - 1,-1):
        s += a[i]
        vp = max2(vp,s)
    
    vf=0
    s=0
    for i in range(y - m):
        s += a[i + m + 1]
        vf =max2(vf ,s)
        
    return max2(vf + vp ,maxAux)

In [13]:
m = [-2, 11, -4, 13, -5, -2]
print (m)
n = sumaMax3(m, 0, len(m)-1)
print (n)

[-2, 11, -4, 13, -5, -2]
20


In [14]:
def max2acct(a,b,acct):
    if a<b:
        acct.count()
        return b
    else:
        return a
    
def sumaMax3acct(a,x,y,acct):
    if x > y:
        acct.count()
        return 0
    if x == y:
        acct.count()
        return max2acct(0,a[x],acct)
    m = ((x + y)/2)
    acct.count()
    
    maxAux= max2acct(sumaMax3acct(a,x,m,acct),
                 sumaMax3acct(a,m + 1,y,acct),acct)
    acct.count()
    
    vp=0; acct.count()
    s=0; acct.count()
    for i in range(m,x - 1,-1):
        acct.count()
        s += a[i]; acct.count()
        vp = max2acct(vp,s,acct); acct.count()
    
    vf=0; acct.count()
    s=0; acct.count()
    for i in range(y - m):
        acct.count()
        s += a[i + m + 1]; acct.count()
        vf =max2acct(vf ,s,acct); acct.count()
        
    return max2acct(vf + vp ,maxAux,acct)

In [15]:
acct= Counter()
m = [-2, 11, -4, 13, -5, -2]
print (m)
n = sumaMax3acct(m, 0, len(m)-1,acct)
print (n)

acct.print_steps()

[-2, 11, -4, 13, -5, -2]
20
Number of steps = 95
